### ISSUE TITLE
Couldn't instantiate App::Monitoring::Plugin::CheckRaid::Plugins::aaccli: untie attempted while 1 inner references still exist at /usr/share/perl/5.24/IPC/Open3.pm line 138

### ISSUE THREAD

**Issue by kolomparrudi** [glensc/nagios-plugin-check_raid#179]
Hi,

I'm trying to use check_raid in debian stretch with nagios 3.5.1.
When I run the script from shell with nagios user it works fine, but when nagios runs it I got this error:

**ePN /usr/lib/nagios/plugins/check_raid: "Couldn't instantiate App::Monitoring::Plugin::CheckRaid::Plugins::aaccli: untie attempted while 1 inner references still exist at /usr/share/perl/5.24/IPC/Open3.pm line 138

Tried with the latest released verison and with latest dev version too.
Any idea what is the problem?

Thanks,
kolomparrudi

**Comment by glensc** [comment]
the plugin was designed to take commands from stdin, perhaps it can now be invoked via commandline?

does this work, and can you provide full output:
```
# aaccli container list /full
```

**Comment by kolomparrudi** [comment]
I have ony arcconf and it works fine.

When I run check_raid from shell it works, the problem only seen if nagios run it:
root@tomline:~# su nagios -s /bin/bash
nagios@tomline:/root$ /usr/lib/nagios/plugins/check_raid
CRITICAL: arcconf:[Controller:Optimal, Degraded drives:1, Logical Device 1(uj):Degraded, Drives: WD-WMC130D3WUHZ=Online]

**Comment by glensc** [comment]
i do not understand what are you reporting here. what should be fixed in your opinion?

**Comment by kolomparrudi** [comment]
The plugin is not working from nagios, I got this error:

Couldn't instantiate App::Monitoring::Plugin::CheckRaid::Plugins::aaccli: untie attempted while 1 inner references still exist at /usr/share/perl/5.24/IPC/Open3.pm line 138

This is why I opened the ticket.

**Comment by kolomparrudi** [comment]
Hi,

Found the solution/workaround:
I had to disable nagios embedded perl interpreter in nagios.cfg:
enable_embedded_perl=0

**Comment by glensc** [comment]
but then you write in [second](https://github.com/glensc/nagios-plugin-check_raid/issues/179#issuecomment-355243831) comment that it runs under nagios user. meh?
